jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/kb7spring
jdbc.username=root
jdbc.password=1234

# ?? ??? ??
file.upload.location=c:/upload
file.upload.max-file-size=-1
file.upload.max-request-size=-1
file.upload.file-size-threshold=5242880